runtime: nodejs20
env: standard

instance_class: F1  # smallest, cost-effective

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 2

entrypoint: node src/server.js
