runtime: nodejs20
env: standard

instance_class: F1  # smallest/cost-effective

automatic_scaling:
  min_instances: 1
  max_instances: 1

entrypoint: node src/server.js

env_variables:
  # ─────── APP CONFIG ───────
  PORT: "8080"
  NODE_ENV: "production"

  # ─────── MYSQL CONFIG ───────
  MYSQL_HOST: "mysql-281cda23-elysian-d80e.h.aivencloud.com"
  MYSQL_PORT: "26376"
  MYSQL_USER: "avnadmin"
  MYSQL_PASSWORD: "AVNS_QtPLNh4iXI5oKT2DqtF"
  MYSQL_DB: "elysian"

  # ─────── JWT AUTH ───────
  JWT_SECRET: "s3cR3t!@#9v$E2z^T&dLr0*YqW+KbH1PfA%mNgXjUoC6bZiVxSwMtQnJg"

  # ─────── EMAIL SMTP ───────
  EMAIL_USER: "elysian.jewelry.eg@gmail.com"
  EMAIL_PASS: "agwyvxpqwbaedfbe"

  # ─────── MONGODB ATLAS ───────
  MONGO_URI: "mongodb+srv://elysianjewelryeg:8kzlEq5TmRS56zCQ@elysian.ot700qr.mongodb.net/?retryWrites=true&w=majority&appName=elysian"

  # ─────── GOOGLE SHEETS ───────
  GOOGLE_SPREAD_SHEET_ID: "1MVZJN51zzYDAeRpzrpPFGJ0dyOdm1Zxk1Jksv9nRWwM"
  GOOGLE_PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC2vPRzzIBTqjJU\nzn7D0PmlEbCYaOl0v/++K6tMiPy3V8ZgMYJo/yRzuAj1eG+arFFLqlp3+3+7FbM8\nr/zQ8fcCvaUv/lynE9nIeIhhxIn+/6pl1FW0QPxPxEVS0p0PxPRBiUzZZIOFcbdK\nJKqowJtxQdSn11CkKSFvt7wxfQM7WqNiyeMY3zmYVi1fUSzkOUyvwmjh98RA/Xe6\ndpsgj1/QQCadv9hc9dPg9ssBW+NDOCUfqMNsCHkOa9rOyof6gBhJonXewR5B05Px\neqn7Co3uR7kLO7KgXtg7tMO/hHkh6v1rgYSDWpPHTPtgQcxO7K2aKYqh3E1zTXfU\niL+UXZzhAgMBAAECggEAPUCeEfiw5RpuD4Y98IYqP/3re1LjOhqnb0e0/g0G5K/b\n01+VDnvDbLR58EoD4s0y3NGHzKL1IDE4aLW24RTSDs2hwrIYvXpGbE+Wq2rVNK/f\nHo3rgmWsDVLFR+tH8UK7+wG6TD5IZaEF5qjeuX0CPZbq4K2oHraYuhlU0CPOwwRf\nbd+Bt5/vId68FtqWCDXT3wtomtisAD3W6OdUi5fA8aomLkLccpJj3sKZCh4OIfR8\nhZr3jmIHQ8tW9HIQHiuTn7Jysxh8vJ6qD66K/hoJh6aHLH2CbUj6MZ/BQ4hlOzWq\nyOIk4+aBCZeMDTZSUbAhqb0/JHfwa3uQfouud+LYtwKBgQDvw4Xd7IwF4U+wcZ0O\n/WSobmOGBImroIM4y0/5JLED9Xm6ETDcymmqWGBXq7oMkgGkfFkH8tnkUctlY1yv\nNygYDol+X+Dl0oT6PpIsT4vltNifYPLQAROVKBa/fHeH0ytFFM2ljNSiLXXEiqCw\nyP04plnrdPE88ZI3XZXFxo3eEwKBgQDDHNnrTPiCx+sznWWPtQNiF/lP1ajj6bRj\nvTrhpfR1mqfwp7MAYV2PbMPg5iEvoFxFooHqpJoqRZQUZPqHKvWTwZK6++A0da1H\nHJrbydEoOCDLy7X7Lz72P81pvmbexXiOvBzmxrQ4iQAR6bW9ZCtyBGakUubwvu+s\n+0MGKWqnuwKBgGjfgxxxLUYdKXgqGeLGn1K1Bj9GmNlDWmJrO83kaLEsnFPw1Qie\nWN2zzmBKsxRwgNtrsJ2zce9Wf7sXXSEe5SCwqx9l3L9p99RlrhZHrQ+KrP35r/uf\nnOsvH9QeI0J78X9D/DefhBpz/AE+Cc+J+oje6pH9Es/vcl9ZRfu+P6uVAoGASpC+\nH5S87I4mrwUaCT+uWVC8MOyArQllrTBmTlI0CLXgNLKCUETlkqiIe2y3hhIM8XfX\nmqrpV/pbSygELqAWVi+GOfuEhcfrPuAJtrF8Q5ifwALMO4Ck2Uss35qqibyCBFqT\n2QZbXbfN1QqyL/0WNW7FI0ujgqIVytADn1k4r30CgYEA2LhKob2y7TWdxxHZMfDS\ne61gsXtnq0CJQcUYD8geCVEwL0qmXL8Vjm94h+V4aj9nkr40cKsyUwchUv8trp5N\nuGgRANNG+iGBeojKl1+tyiYkYUNtyYrya+42etdZtDH/wV7ubg5A6Ljx6KMOAXE+\nSkvDfcMOU5qwyvvLbowohY0=\n-----END PRIVATE KEY-----\n"
  GOOGLE_CLIENT_EMAIL: "elysian-api@appspot.gserviceaccount.com"